### ISSUE TITLE
Kaskara issues on coreutils/gnubug_26545 

### ISSUE THREAD

**Issue by pdreiter** [squaresLab/Kaskara#58]
Using darjeeling i.e. `pipenv run darjeeling repair bugs/vulnloc/coreutils/gnubug_26545/repair.darjeeling.yml` from git@github.com:squaresLab/security-repair-benchmarks.git 
Looks like clang analyzer is failing to generate a `statements.json` file. No other information is provided in stderr output.
```
58417 /workspace/source/src/shred.c:1220:31: warning: missing field 'n_iterations' initializer [-Wmissing-field-initializers      ]
58418   struct Options flags = { 0, };
58419                               ^
58420 visiting file: /workspace/source/src/shred.c
58421 /opt/kaskara/scripts/kaskara-statement-finder: line 5:    58 Segmentation fault      (core dumped) /opt/kaskara/bin/kaskara-statement-finder "$@"
58422 Error: No such container:path: 75841137dfa6d0bccee13a40964d4a9e37f19b8ff651f6a82b99b8ac285a69c7:/workspace/source/statements.json
58423 Traceback (most recent call last):
58424   File "/home/pdreiter/.local/share/virtualenvs/secrepben-_P0VbZEL/lib/python3.9/site-packages/dockerblade/files.py",       line 128, in copy_to_host
58425     subprocess.check_call(cmd, shell=True)
58426   File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
58427     raise CalledProcessError(retcode, cmd)
58428 subprocess.CalledProcessError: Command 'docker cp -L 75841137dfa6d0bccee13a40964d4a9e37f19b8ff651f6a82b99b8ac285a69c7:/workspace/source/statements.json /tmp/tmpzjn0fp__/contents' returned non-zero exit status 1.
58429
```

**Comment by pdreiter** [comment]
other bugs: libtiff/bugzilla_2611

**Comment by ChrisTimperley** [comment]
Hey. Is there a particular reason why you're using security-repair-benchmarks rather than butrs-red-team-evaluation? (And `pipenv run scripts/repair coreutils gnubug_26545`.)

I also see a seg fault (and lots more debugging output + log files) while populating the database when I invoke the bug scenario via the Red Team Evaluation infrastructure:
```
DEBUG: StatementDatabase: adding statement...
DEBUG: obtained statement location: /workspace/source/src/dd.c@278:14::278:36
DEBUG: obtained source for statement: sizeof LONGEST_SYMBOL]
/opt/kaskara/scripts/kaskara-statement-finder: line 5:    56 Segmentation fault      (core dumped) /opt/kaskara/bin/kaskara-statement-finder "$@"
Error: No such container:path: 2a36269c5fc7c07bcf31c76d3aeadff52ecbb023c4ecf5d7816723ed345f25c4:/workspace/source/statements.json
Traceback (most recent call last):
  File "/usr0/home/chris/tools/butrs-evaluation/tools/dockerblade/src/dockerblade/files.py", line 128, in copy_to_host
    subprocess.check_call(cmd, shell=True)
  File "/home/chris/.pyenv/versions/3.9.6/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'docker cp -L 2a36269c5fc7c07bcf31c76d3aeadff52ecbb023c4ecf5d7816723ed345f25c4:/workspace/source/statements.json /tmp/tmpwpiwn12q/contents' returned non-zero exit status 1.DEBUG: StatementDatabase: adding statement...
DEBUG: obtained statement location: /workspace/source/src/dd.c@278:14::278:36
DEBUG: obtained source for statement: sizeof LONGEST_SYMBOL]
/opt/kaskara/scripts/kaskara-statement-finder: line 5:    56 Segmentation fault      (core dumped) /opt/kaskara/bin/kaskara-statement-finder "$@"
Error: No such container:path: 2a36269c5fc7c07bcf31c76d3aeadff52ecbb023c4ecf5d7816723ed345f25c4:/workspace/source/statements.json
Traceback (most recent call last):
  File "/usr0/home/chris/tools/butrs-evaluation/tools/dockerblade/src/dockerblade/files.py", line 128, in copy_to_host
    subprocess.check_call(cmd, shell=True)
  File "/home/chris/.pyenv/versions/3.9.6/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'docker cp -L 2a36269c5fc7c07bcf31c76d3aeadff52ecbb023c4ecf5d7816723ed345f25c4:/workspace/source/statements.json /tmp/tmpwpiwn12q/contents' returned non-zero exit status 1.
```

**Comment by pdreiter** [comment]
hey @ChrisTimperley - this is from 2022 :) I don't remember the details!
